import type { Metadata } from 'next';
import { Geist, Geist_Mono, Inter, Newsreader } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { Toaster } from '@/components/ui/sonner';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const newsreader = Newsreader({
    subsets: ['latin'],
    variable: '--font-serif',
    style: ['normal', 'italic'],
});

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={cn(
                'h-full',
                'antialiased',
                geistSans.variable,
                geistMono.variable,
                'font-sans',
                inter.variable,
                newsreader.variable,
            )}
        >
            <body className="min-h-full flex flex-col">
                {children}
                <Toaster />
            </body>
        </html>
    );
}
